# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: ko # 한국말로 설정
early_access: false
reviews:
  profile: "chill" # 리뷰 적당하게 한다는 뜻
  request_changes_workflow: true # 코드래빗이 리뷰 끝나면 알아서 PR 승인하게끔
  high_level_summary: true # 전체 요약 코멘트 작성
  review_status: false # 각 파일/라인에 대해 "좋음 / 개선 필요 " 등 뱃지 표시
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches: [] # 빈 배열로 설정하면 모든 브랜치 자동 리뷰 활성화
chat:
  auto_reply: true
